---
title: "R Notebook"
output: html_notebook
---
```{r import and name}
getwd()
library(tidyverse)
eps <- read.csv('./SGStats/eps.csv')
queens <- read.csv('./SGStats/queens.csv')
names(queens) <- queens[1,]
queens <- queens[-1,]
colnames(queens)[2] <- 'queen'
chars <- read.csv('./SGStats/chars.csv')
```


```{r look at eps}
sapply(eps, class)
eps$airdate <- as.Date(eps$airdate)
eps$regas <- as.factor(eps$regas)
eps$internat <- as.factor(eps$internat)
eps$specialformat <- as.factor(eps$specialformat)
summary(eps)
```
```{r look at queens}
sapply(queens, class)
queens$character2[queens$character2 == "N/A"] <- NA
queens$uniqueid <- as.numeric(queens$uniqueid)
```

```{r look at chars}
sapply(chars, class)
chars$alive <- as.factor(chars$alive)
chars$genre <- as.factor(chars$genre)
chars$genre2 <- as.factor(chars$genre2)
chars$genre3 <- as.factor(chars$genre3)
chars1 <- chars[1:5]
chars2 <- chars[, -c(3:5)]
chars1
chars2
```

```{r eppivot}
#eps[10:31]
epspivot <- pivot_longer(eps, cols = 10:31, names_to = 'plcmnt', values_to = 'queen', values_drop_na = T) %>% filter(queen != 'N/A')
```

```{r queenpivot}
queenspivot <- pivot_longer(queens, cols = 3:4, values_to = 'character') %>% drop_na(character) %>% select(c(1, 2, 4))
```

```{r char1pivot}
chars1[4:5][chars1[4:5] == "N/A"] <- NA
char1pivot <- pivot_longer(chars1, cols = 3:5, values_to = 'genres') %>% drop_na(genres)
char1pivot <- char1pivot[-3]
```
```{r char2pivot}
char2pivot <- pivot_longer(chars2, cols = 3:13, values_to = 'genres') %>% drop_na(genres)
char2pivot = char2pivot[-4]
char2pivot <- char2pivot %>% rename('genres' = 'name')
```


```{r epqueen Join}
epqueenjoin <- inner_join(epspivot, queenspivot, by = c('uniqueid', 'queen'), multiple = 'all')
myby <- join_by(character == char)
bigjoin1 <- inner_join(epqueenjoin, char1pivot, myby)
bigjoin2 <- inner_join(epqueenjoin, char2pivot, myby)
bigjoin2$genres <- as.factor(bigjoin2$genres)
summary(bigjoin2)
```
```{r summarize placements}
bigjoin1 <- bigjoin1 %>%
  mutate(tsb = case_when(startsWith(tolower(plcmnt), 'safe') ~ 'SAFE',
                         startsWith(tolower(plcmnt), 'win') ~ 'WIN',
                         startsWith(tolower(plcmnt), 'high') ~ 'HIGH',
                         startsWith(tolower(plcmnt), 'bottom') ~ 'BOTTOM',
                          startsWith(tolower(plcmnt), 'elim') ~ 'ELIM'))

bigjoin2 <- bigjoin2 %>%
  mutate(tsb = case_when(startsWith(tolower(plcmnt), 'safe') ~ 'SAFE',
                         startsWith(tolower(plcmnt), 'win') ~ 'WIN',
                         startsWith(tolower(plcmnt), 'high') ~ 'HIGH',
                         startsWith(tolower(plcmnt), 'bottom') ~ 'BOTTOM',
                          startsWith(tolower(plcmnt), 'elim') ~ 'ELIM'))
```

```{r make and order factors}
bigjoin1$tsb <- factor(bigjoin1$tsb, levels = c('ELIM', 'BOTTOM', 'SAFE', 'HIGH', 'WIN'))
bigjoin2$tsb <- factor(bigjoin2$tsb, levels = c('ELIM', 'BOTTOM', 'SAFE', 'HIGH', 'WIN'))
#summary(bigjoin)
```
```{r pt values}
bigjoin1 <- bigjoin1 %>%
  mutate(score = case_when(tsb == 'WIN' ~ 1,
                         tsb == 'HIGH' ~ .5,
                         tsb == 'SAFE' ~ 0,
                         tsb == 'BOTTOM' ~ -.5,
                         tsb == 'ELIM' ~ -1))
bigjoin1 %>% group_by(genres) %>% summarise(avgscore = mean(score)) %>% arrange(desc(avgscore))

bigjoin2 <- bigjoin2 %>%
  mutate(score = case_when(tsb == 'WIN' ~ 1,
                         tsb == 'HIGH' ~ .5,
                         tsb == 'SAFE' ~ 0,
                         tsb == 'BOTTOM' ~ -.5,
                         tsb == 'ELIM' ~ -1))
bigjoin2 %>% group_by(genres) %>% summarise(avgscore = mean(score)) %>% arrange(desc(avgscore))
```
```{r}
write.csv(bigjoin1, 'bigjoin1.csv', row.names=F)
write.csv(bigjoin2, 'bigjoin2.csv', row.names=F)
```

```{r PLOT1}
#439 results approx normally distributed- separate entry for each genre that each character is in, 
summary(bigjoin1$tsb)
summary(bigjoin2$tsb)
plot(bigjoin1$tsb)
plot(bigjoin2$tsb)
```


```{r PLOT2}
#I'd like to have an option to disregard All Stars or Canada (non-Ru) regular (bigjoin %>% filter(regas == 'reg') %>% group_by(tsb))

#-----
#one entry for each genre within a character
bigjoin2 %>% group_by(tsb) %>% ggplot(., aes(x = tsb)) + geom_bar()

#Score instead of placement (same)
bigjoin2 %>% group_by(score) %>% ggplot(., aes(x = score)) + geom_bar()
#------
#what about how all the QUEENS overall have done, disregarding characters? (BthDQ has one win)
bigjoin1 %>% distinct(uniqueid, queen, tsb) %>% group_by(queen) %>% ggplot(aes(x = tsb)) + geom_bar()
bigjoin1 %>% distinct(uniqueid, queen, tsb) %>% group_by(queen)

bigjoin2 %>% distinct(uniqueid, queen, tsb) %>% group_by(queen) %>% ggplot(aes(x = tsb)) + geom_bar()
bigjoin2 %>% distinct(uniqueid, queen, tsb) %>% group_by(queen)

#what about how distinct CHARACTERS do? (entry for each character in every episode)
bigjoin2 %>% distinct(uniqueid, character, tsb) %>% ggplot(aes(x = tsb)) + geom_bar()
bigjoin2 %>% distinct(uniqueid, character, tsb)
```
```{r Fullfacet take two- potential!}
library('scales')
#fullfacet <- bigjoin2 %>% group_by(tsb) %>% ggplot(aes(tsb), labels = TRUE) + geom_bar(aes(y = (..count..)/tapply(..count..,..PANEL..,sum)[..PANEL..])) + stat_bin(aes(stat='count'), vjust = 0, geom='text', position='identity') 
#fullfacet

ff <- bigjoin2 %>% group_by(tsb) %>% ggplot(aes(tsb), labels = TRUE) + geom_bar()
ff <- ff + geom_text(aes(label=..count..), stat='count', y = 114) + facet_wrap(~genres)

#+ facet_wrap(~genres)
#fullfacet
geom_bar(aes(y = (..count..)/tapply(..count..,..PANEL..,sum)[..PANEL..]))

ff
ff %+% dplyr::filter(bigjoin2, genres %in% c('fashion', 'histfict'))
```







```{r, PHASE OUT- scared to delete, eval = FALSE}
#Multi-hyphenates counted multiple times, how do different genres do?
fullfacet <- bigjoin %>% group_by(tsb) %>% ggplot(aes(tsb)) + geom_bar() + facet_wrap(~genres)
#, scales = 'free_y')
fullfacet
#subsets
fullfacet %+% dplyr::filter(bigjoin, genres %in% c('Actor', 'GG'))
#^this is good, but you have to go through the fullfacet, takes a longer time

#close, totals all of them (phase this out)
addcounts <- genrecheck %>% ggplot(aes(x=tsb), fill = genres, group = genres) + geom_bar() + labs(caption = paste("Total =", nrow(genrecheck))) + facet_wrap(~genres)
addcounts

genrebar <- genrecheck %>% ggplot(aes(x=tsb), fill = genres, group = genres) + geom_bar() + facet_wrap(~genres)
genrebar
```

```{r CRUX- Phase out}
#examine genres- double check
#bigjoin %>% filter(genres == 'TV')
#--------------------------------------------------------------
genrecheck <- bigjoin1 %>% distinct(uniqueid, character, tsb, score, genres)
genrecheck <- genrecheck %>% filter(genres %in% c('Reality', 'Government'))
genrecheck

genredens <- genrecheck %>% ggplot(., aes(x=tsb, group=genres, fill = genres)) + geom_bar()
genredens
#--------------------------------------------------------------
genrebar <- genrecheck %>% group_by(genres) %>% mutate(genre_count = n()) %>%
  ungroup() %>%
  mutate(genre_update = paste0(genres, "; n=", genre_count)) %>%
  ggplot(aes(x = tsb)) + geom_bar()+ facet_wrap(~genre_update)
genrebar
```
```{r CRUX2}
#examine genres- double check
#bigjoin %>% filter(genres == 'TV')
#------------

#For RuPaul Only
#bigjoin1 %>% filter(internat != 'CAN')
#Disregard All-Stars Formats
#bigjoin1 %>% filter(regas == 'reg')

#--------------------------------------------------------------
genrecheck <- bigjoin2 %>% distinct(uniqueid, season, internat, queen, character, tsb, score, genres)
genrecheck <- genrecheck %>% filter(genres %in% c('musician', 'pubfig'))
#--------------------------------------------------------------
genrebar <- genrecheck %>% group_by(genres) %>% mutate(genre_count = n(), avgscore = round(mean(score), 3)) %>%
  ungroup() %>%
  mutate(genre_update = paste0(genres, "; n=", genre_count, "; Mean Score: ", avgscore)) %>%
  ggplot(aes(x = tsb)) + geom_bar()+ scale_y_continuous(breaks= pretty_breaks()) + facet_wrap(~genre_update) + labs(title = 'Genre Comparison by Count', x = 'Placement', y = 'Count')
genrebar
#^THIS IS GOOD

#---------------------
ggplot(genrecheck %>% group_by(genres) %>% mutate(weight = 1/n()), 
       aes(x = tsb, fill = genres)) +
  geom_bar(aes(weight = weight), stat = 'count', position = 'dodge') + labs(title = 'Percent Placement by Genre', x = 'Placement', y = 'Percentage')

#---
genrecheck %>% group_by(genres) %>% mutate(weight = 1/n()) %>%
         ggplot(aes(x = tsb, fill = genres)) + geom_bar(aes(weight = weight), stat = 'count', position = 'dodge') + 
    labs(title = 'Percent Placement by Genre', x = 'Placement', y = 'Percentage')

```
```{r TABLE TAB BEHIND THESE PLOTS- ADD QUEENS}
genrecheck %>% group_by(genres) %>% select(-1)
```



```{r genre re-re-examine}
summary(bigjoin2)
bigjoin2 %>% filter(genres == 'entertainer')
```

```{r T-TESTING}
### I am suspicious of trying to do t-testing on this, because 
#install.packages('rstatix')
library(rstatix)
genrecheck2 <- bigjoin2 %>% distinct(uniqueid, character, tsb, score, genres)
genrecheck2
genrecheck2 %>% filter(genres == 'writer')
genrecheck2$score
genrecheck2 %>% group_by(genres) %>% get_summary_stats(score, type = "mean_sd")
genreanova <- genrecheck2 %>% anova_test(score ~ genres)
genreanova #p-value here is .027, there are statistically-significant differences between the groups!

```


```{r T-TESTING, Pairwise}
#pairwise comparisons OK I am struggling here. Can't get much out of these pairwise comparisons, which I guess is ok? but the anova says there's a statistically-significant difference among the groups.
#trimmedgc <- genrecheck %>% group_by(genres) %>% filter(n() >= 2) %>% ungroup()
#trimmedgc
#trimmedgc$score <- as.numeric(trimmedgc$score)
#?pairwise.t.test

pw <- pairwise.t.test(genrecheck2$score, genrecheck2$genres, p.adj= 'none')
pwc

mytest <- data.table(pwc[['p.value']], keep.rownames = T) %>% rename(X = rn) %>% mutate_if(is.numeric, ~round(., 4))
mytest




pvalues$comedicent = as.numeric(pvalues$comedicent)
pvalues$tv = as.numeric(pvalues$tv)
pvalues
  
class(trimmedgc$score)
#wilcox.test(trimmedgc$score,trimmedgc$genres, p.adj= 'bonferroni') 
```

```{r DEAD VS ALIVE- plots and t-testing}
#Dead Characters vs Alive Characters (at first appearance)
bigjoin %>% distinct(uniqueid, character, tsb, alive) %>% ggplot(aes(x = tsb)) + geom_bar() + facet_wrap(~alive)


deadalivecheck <- bigjoin2 %>% distinct(uniqueid, character, score, alive)
doa <- ggplot(data = deadalivecheck, aes(x=score, group=alive, fill = alive)) + geom_bar(position = 'dodge')
doa

#T-TESTING
deadalivecheck
deadalivecheck %>% group_by(alive) %>% summarise(mean(score))
deadalivecheck %>% summarise(mean(score))
?t.test
allalive <- deadalivecheck %>% filter(alive == 1)
allalive
alldead <- deadalivecheck %>% filter(alive == 0)
alldead
class(alldead$score)
class(allalive$score)
mydoa <- t.test(alldead$score, allalive$score) #pval is .02- dead character avg is significantly different from alive character avg
mydoa
round(mydoa[['p.value']], 4)

t.test(allalive$score, deadalivecheck$score) #pval is .3822, alive characters don't differ significantly from the whole group
t.test(alldead$score, deadalivecheck$score) #pval is .09151, dead characters don't differ significantly from whole group
```
```{r}

deadalivecheck <- bigjoin2 %>% distinct(uniqueid, character, tsb, score, alive)

ggplot(data = deadalivecheck, aes(x=tsb, group=alive, fill = alive)) + geom_bar(position = 'dodge')

deadalivecheck %>% ggplot(aes(x = tsb, group=alive, fill = alive)) + geom_bar(position = 'dodge') +
  scale_y_continuous(breaks = pretty_breaks()) + scale_fill_manual(values = c("#8344AD", "#27AE60")) +
  scale_fill_discrete(name = "", labels=c('dead', 'alive'))
#---
deadalivecheck %>% group_by(alive) %>% mutate(weight = 1/n()) %>%
         ggplot(aes(x = tsb, fill = alive)) + geom_bar(aes(weight = weight), stat = 'count', position = 'dodge') + 
    labs(title = 'Percent Placement by Genre', x = 'Placement', y = 'Percentage')


deadalivecheck %>% group_by(alive) %>% mutate(weight = 1/n()) %>%
  ggplot(aes(x = tsb, fill = alive)) + geom_bar(aes(weight = weight), stat = 'count', position = 'dodge') +
  scale_fill_manual(values = c("#8344AD", "#27AE60")) +
  labs(title = 'Dead Characters Tend to Perform Better', x = 'Placement', y = 'Percentage')

```
```{r}
deadalivecheck <- bigjoin2 %>% distinct(uniqueid, character, tsb, score, alive)

deadalivecheck %>% group_by(alive) %>% mutate(avgscore = round(mean(score), 3)) %>%
    ungroup() %>% mutate(alive_update = paste0("Mean Score: ", avgscore)) %>%
    ggplot(aes(x = tsb, fill = alive)) + scale_fill_manual(values = c("#8344AD", "#27AE60"), name = "", labels=c('dead', 'alive')) + geom_bar()+ scale_y_continuous(breaks= pretty_breaks()) + facet_wrap(~alive_update) + 
    labs(title = "Dead Characters' Advantage is Statistically Significant", x = 'Placement', y = 'Count')

deadalivecheck %>% group_by(alive) %>% mutate(weight = 1/n()) %>%
  ggplot(aes(x = tsb, fill = alive)) + geom_bar(aes(weight = weight), stat = 'count', position = 'dodge') +
  scale_fill_manual(values = c("#8344AD", "#27AE60"), name = "", labels = c('dead', 'alive')) +
  labs(title = 'Dead Characters Tend to Perform Better', x = 'Placement', y = 'Percentage')

```

```{r}

```

```{r genres, t-testing}
bigjoin %>% group_by(genres) %>% summarise(avgscore = mean(score)) %>% arrange(desc(avgscore))
genregroup <- bigjoin %>% group_by(genres)
genregroup
genregroup %>% summarise(mean(score))
genregroup$score

genregroup %>%filter (genres == 'Musician') %>% pull(score)
athletes <- genregroup %>% filter(genres == 'Writer') %>% pull(score)
athletes
t.test(athletes, genregroup$score)
```

```{r}
#sure you can just have everyone who won but really what you want is people who have done well over multiple SG's
this <- bigjoin %>% group_by(uniqueid, queen) %>% summarise()  #distinct(uniqueid, queen)
this2 <- bigjoin%>% group_by(uniqueid)

#This is just the queens who have done more than one (join on this and get some more interesting stats)
twotimers <- queens %>% filter(duplicated(queen, fromLast = T) | duplicated(queen, fromLast = F))
twotimers <- twotimers[-4]
```

```{r}
#hmm this is cool and really close but the mutliple characters are going to throw off the avg
bigjoin %>% filter(queen %in% twotimers$dq) %>% distinct(uniqueid, queen, score) %>% group_by(queen) %>% summarise(avgscore = mean(score)) %>% arrange(desc(avgscore))

bigjoin %>% filter(queen == 'Gia Gunn')
```


